# Generated by Django 5.1.4 on 2025-01-23 19:21

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
        ('KMO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='idrwway',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idrwstation', chained_model_field='idrwstation', on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwway'),
        ),
    ]
