# Generated by Django 5.1.4 on 2025-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='eliminated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Устранено'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='image_defect',
            field=models.ImageField(blank=True, upload_to='kmo_imgs/<django.db.models.fields.DateField>', verbose_name='Фотография неисправности'),
        ),
    ]
