# Generated by Django 5.1.4 on 2025-01-24 20:51

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
        ('KMO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='RW_thread',
            field=models.CharField(choices=[('правая', 'правая'), ('правая', 'левая')], max_length=6, verbose_name='Нитка'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='idrwsp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idrwsp', chained_model_field='idrwstation', on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwsp'),
        ),
    ]
