# Generated by Django 5.1.4 on 2025-01-30 11:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
        ('KMO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='idBs_RW_defect_tp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idBs_RW_defect_gr', chained_model_field='id_RW_defect_gr', on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rw_defect_tp'),
        ),
    ]
