# Generated by Django 5.1.4 on 2025-01-30 13:17

import KMO.models
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_obj_insp_s_create_user_and_more'),
        ('KMO', '0002_alter_kmodet_idbs_rw_defect_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='RW_picket',
            field=models.CharField(blank=True, choices=[('-', '---------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='пикет'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='RW_thread',
            field=models.CharField(blank=True, choices=[('правая', 'правая'), ('правая', 'левая')], max_length=6, null=True, verbose_name='Нитка'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='RW_unit',
            field=models.CharField(blank=True, choices=[('-', '---------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True, verbose_name='Звено'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='idrwsp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='idrwstation', chained_model_field='idrwstation', null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwsp'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='idrwway',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='idrwstation', chained_model_field='idrwstation', null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwway'),
        ),
        migrations.AlterField(
            model_name='kmodet',
            name='image_defect',
            field=models.ImageField(blank=True, null=True, upload_to=KMO.models.custom_path, verbose_name='Фотография неисправности'),
        ),
    ]
