# Generated by Django 5.1.4 on 2025-01-24 20:58

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_rwsp_idrwstation'),
        ('KMO', '0002_alter_kmodet_rw_thread_alter_kmodet_idrwsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='idrwsp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idrwstation', chained_model_field='idrwsp', on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwsp'),
        ),
    ]
