# Generated by Django 5.1.4 on 2025-01-27 15:57

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0003_alter_bs_rw_defect_gr_s_name_and_more'),
        ('KMO', '0003_alter_kmodet_idrwsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='idrwsp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idrwstation', chained_model_field='idrwstation', on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwsp'),
        ),
    ]
