# Generated by Django 5.1.4 on 2025-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMO', '0004_alter_kmodet_idrwsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmo',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Утверждён'),
        ),
    ]
