# Generated by Django 5.1.4 on 2025-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMO', '0006_alter_kmodet_image_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmodet',
            name='image_defect',
            field=models.ImageField(blank=True, upload_to='kmo_imgs/testf', verbose_name='Фотография неисправности'),
        ),
    ]
