# Generated by Django 5.1.4 on 2025-01-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0002_bar_code_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar_code',
            name='station',
        ),
    ]
