# Generated by Django 5.1.4 on 2025-01-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_obj_insp_s_create_user_and_more'),
        ('qrgenerator', '0003_remove_bar_code_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_code',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BS.bs_rwstation', verbose_name='Станция'),
            preserve_default=False,
        ),
    ]
