# Generated by Django 5.1.4 on 2025-01-31 11:08

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_obj_insp_s_create_user_and_more'),
        ('qrgenerator', '0005_bar_code_iddepowner_alter_bar_code_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_code',
            name='station',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='iddepowner', chained_model_field='iddepowner', null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwstation'),
        ),
    ]
