# Generated by Django 5.1.4 on 2025-01-31 11:35

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_obj_insp_s_create_user_and_more'),
        ('qrgenerator', '0007_bar_code_idrwsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_code',
            name='idrwway',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='station', chained_model_field='idrwstation', null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwway'),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='idobject',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id объекта'),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='idrwsp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='station', chained_model_field='idrwstation', null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rwsp'),
        ),
    ]
