# Generated by Django 5.1.4 on 2025-01-29 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('d_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('d_hiring', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('d_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('s_create_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('chairman', models.BooleanField(default=False, verbose_name='Является председателем')),
                ('member_kmo', models.BooleanField(default=False, verbose_name='Является членом комиссии')),
                ('iddepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_department', verbose_name='Подразделение')),
                ('iddepowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_depowner', verbose_name='Филиал')),
                ('idposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_position', verbose_name='Должность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
