# Generated by Django 5.1.4 on 2025-01-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bs_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=50, verbose_name='Подразделение')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('part_kmo', models.BooleanField(default=False, verbose_name='Участвует в КМО')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Bs_depowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=30, verbose_name='Филиал')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Bs_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=90, verbose_name='Должность')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Bs_RW_defect_gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=50, verbose_name='Группа Неисправности')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
            ],
            options={
                'verbose_name': 'Группа Неисправности или отклонения',
                'verbose_name_plural': 'Группа Неисправностей или отклонений',
            },
        ),
        migrations.CreateModel(
            name='Bs_Obj_insp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=30, verbose_name='Объекты  осмотра')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('iddepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_department', verbose_name='Служба')),
            ],
            options={
                'verbose_name': 'Объект  осмотра',
                'verbose_name_plural': 'Объекты  осмотра',
            },
        ),
        migrations.CreateModel(
            name='Bs_RW_defect_tp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=100, verbose_name='Вид неисправности')),
                ('s_deviation_interval', models.CharField(max_length=5, null=True, verbose_name='Интервал отклонения')),
                ('s_deviation_interval_dop', models.CharField(max_length=5, null=True, verbose_name='Интервал отклонения_2')),
                ('d_deadline', models.CharField(max_length=3, null=True, verbose_name='Крайний срок (в днях)')),
                ('s_measurement', models.CharField(max_length=3, null=True, verbose_name='Единица измерения')),
                ('n_speed_limit', models.IntegerField(null=True, verbose_name='Ограничение скорости')),
                ('s_create_user', models.CharField(max_length=25, null=True, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, null=True, verbose_name='Недействующий')),
                ('id_RW_defect_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rw_defect_gr', verbose_name='Группа Неисправности')),
            ],
            options={
                'verbose_name': 'Вид Неисправности или отклонения',
                'verbose_name_plural': 'Вид Неисправностей или отклонений',
            },
        ),
        migrations.CreateModel(
            name='Bs_RW_element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=30, verbose_name='Элемент осмотра')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('id_obj_insp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BS.bs_obj_insp', verbose_name='Объект осмотра')),
            ],
            options={
                'verbose_name': 'Элемент осмотра',
                'verbose_name_plural': 'Элементы осмотра',
            },
        ),
        migrations.AddField(
            model_name='bs_rw_defect_gr',
            name='id_rw_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BS.bs_rw_element', verbose_name='Элемент осмотра'),
        ),
        migrations.CreateModel(
            name='Bs_RWStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(max_length=10, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=70, verbose_name='Станция/Участок')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('iddepowner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BS.bs_depowner', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'ЖД станция/участок',
                'verbose_name_plural': 'ЖД станции/участки',
            },
        ),
        migrations.CreateModel(
            name='Bs_RWstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='мнемокод')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('left_border', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_border', to='BS.bs_rwstation', verbose_name='Чётная граница')),
                ('right_border', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_border', to='BS.bs_rwstation', verbose_name='Нечётная граница')),
            ],
            options={
                'verbose_name': 'ЖД перегон',
                'verbose_name_plural': 'ЖД перегоны',
            },
        ),
        migrations.CreateModel(
            name='Bs_RWkilometr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=5, verbose_name='км')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('idrwstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_rwstation', verbose_name='Станция/участок')),
            ],
            options={
                'verbose_name': 'км станции',
                'verbose_name_plural': 'км-ы станции',
            },
        ),
        migrations.CreateModel(
            name='Bs_RWway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=10, verbose_name='Путь')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('idrwstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_rwstation', verbose_name='Станция/участок')),
            ],
            options={
                'verbose_name': 'ЖД путь',
                'verbose_name_plural': 'ЖД пути',
            },
        ),
        migrations.CreateModel(
            name='Bs_RWsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mnemocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='мнемокод')),
                ('s_name', models.CharField(max_length=5, verbose_name='Стрелочный перевод')),
                ('s_create_user', models.CharField(max_length=25, verbose_name='Создатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Изменивший')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('not_used', models.BooleanField(default=False, verbose_name='Недействующий')),
                ('idrwstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_rwway', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Стрелочный перевод',
                'verbose_name_plural': 'Стрелочные переводы',
            },
        ),
    ]
