# Generated by Django 5.1.4 on 2025-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs_obj_insp',
            name='s_create_user',
            field=models.CharField(max_length=35, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='bs_obj_insp',
            name='s_mnemocode',
            field=models.CharField(max_length=12, verbose_name='мнемокод'),
        ),
        migrations.AlterField(
            model_name='bs_obj_insp',
            name='s_name',
            field=models.CharField(max_length=40, verbose_name='Объекты  осмотра'),
        ),
        migrations.AlterField(
            model_name='bs_obj_insp',
            name='s_update_user',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Изменивший'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_gr',
            name='s_create_user',
            field=models.CharField(max_length=35, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_gr',
            name='s_mnemocode',
            field=models.CharField(max_length=12, verbose_name='мнемокод'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_gr',
            name='s_name',
            field=models.CharField(max_length=250, verbose_name='Группа Неисправности'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_gr',
            name='s_update_user',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Изменивший'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='d_deadline',
            field=models.CharField(max_length=10, null=True, verbose_name='Крайний срок (в днях)'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='n_speed_limit',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ограничение скорости'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_name',
            field=models.CharField(max_length=350, verbose_name='Вид неисправности'),
        ),
        migrations.AlterField(
            model_name='bs_rw_element',
            name='s_create_user',
            field=models.CharField(max_length=35, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='bs_rw_element',
            name='s_mnemocode',
            field=models.CharField(max_length=12, verbose_name='мнемокод'),
        ),
        migrations.AlterField(
            model_name='bs_rw_element',
            name='s_name',
            field=models.CharField(max_length=40, verbose_name='Элемент осмотра'),
        ),
        migrations.AlterField(
            model_name='bs_rw_element',
            name='s_update_user',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Изменивший'),
        ),
    ]
