# Generated by Django 5.1.4 on 2025-01-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bs_obj_insp',
            name='iddepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_department', verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='d_deadline',
            field=models.CharField(max_length=3, null=True, verbose_name='Крайний срок (в днях)'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='n_speed_limit',
            field=models.IntegerField(null=True, verbose_name='Ограничение скорости'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='not_used',
            field=models.BooleanField(default=False, null=True, verbose_name='Недействующий'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_create_user',
            field=models.CharField(max_length=25, null=True, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_deviation_interval',
            field=models.CharField(max_length=5, null=True, verbose_name='Интервал отклонения'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_deviation_interval_dop',
            field=models.CharField(max_length=5, null=True, verbose_name='Интервал отклонения_2'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_measurement',
            field=models.CharField(max_length=3, null=True, verbose_name='Единица измерения'),
        ),
    ]
