# Generated by Django 5.1.4 on 2025-01-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs_rwsp',
            name='idrwstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BS.bs_rwstation', verbose_name='Станция'),
        ),
    ]
