# Generated by Django 5.1.4 on 2025-01-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_alter_bs_rwsp_idrwstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs_rw_defect_gr',
            name='s_name',
            field=models.CharField(max_length=100, verbose_name='Группа Неисправности'),
        ),
        migrations.AlterField(
            model_name='bs_rw_defect_tp',
            name='s_name',
            field=models.CharField(max_length=150, verbose_name='Вид неисправности'),
        ),
        migrations.AlterField(
            model_name='bs_rwkilometr',
            name='s_name',
            field=models.CharField(max_length=6, verbose_name='км'),
        ),
        migrations.AlterField(
            model_name='bs_rwsp',
            name='s_name',
            field=models.CharField(max_length=8, verbose_name='Стрелочный перевод'),
        ),
    ]
